global:
  scrape_interval: 15s  # Scrape every 15 seconds

scrape_configs:
  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:9100']  # Traefik metrics endpoint

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']  # RabbitMQ metrics endpoint

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']  # PostgreSQL metrics endpoint

  - job_name: 'backend'
    static_configs:
      - targets: ['backend:8000']  # Backend metrics endpoint
