services:
  mongo1:
    build: .
    container_name: mongo1
    networks:
      - mongo-cluster

  mongo2:
    image: mongo
    container_name: mongo2
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    networks:
      - mongo-cluster

  mongo3:
    image: mongo
    container_name: mongo3
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    networks:
      - mongo-cluster


networks:
  mongo-cluster:
    driver: bridge
